/**
 * @author kasmadi
 * @date 27/05/2022
 */

object DevConfigField {
    const val applicationId = "com.fta.dev.rctitv"
    const val SERVICES_URL = "\"dev-api.rctiplus.com\""
    const val SERVICES_NEWS = "\"https://rc-api.rctiplus.com\""
    const val SERVICES_COUNTER = "\"https://hera.mncplus.id\""
    const val SERVICES_UGC = "\"https://dev-api.rctiplus.com\""
    const val SERVICES_UGC_MONETIZATION = "\"https://dev-api.rctiplus.com\""
    const val SERVICES_PAYMENT = "\"https://dev-api-payment.rctiplus.com\""
    const val SERVICES_REWARDS = "\"https://dev-api-rewards.rctiplus.id\""
    const val SERVICES_TUS = "\"http://o-dev-api-tusd.rctiplus.com\""
    const val SERVICES_GRAPHQL = "\"https://hera.mncplus.id/graphql\""
    const val SERVICES_KONG = "\"https://hera.mncplus.id\""
    const val WEBVIEW_NEWS = "\"https://dev-webm.rctiplus.com\""
    const val WEBVIEW_ROOV = "\"https://dev-radioplus.mncplus.com/\""
    const val WEBVIEW_GAMES = "\"https://portal-dev.games.rctiplus.com\""
    const val WEBVIEW_REWARDS = "\"https://dev-rewards.rctiplus.id\""
    const val WEBVIEW_TNC =
        "\"https://microsite.rctiplus.com/rctiplus-terms-and-conditions\""
    const val WEBVIEW_PRIVACY_POLICY =
        "\"https://microsite.rctiplus.com/rctiplus-privacy-policy\""
    const val WEBVIEW_FAQ = "\"https://microsite.rctiplus.com/rctiplus-faq\""
    const val WEBVIEW_TNC_HOT =
        "\"https://dev-webm.rctiplus.com/general/tnc?platform=android&header=0\""
    const val WEBVIEW_PRIVACY_POLICY_HOT =
        "\"https://dev-webm.rctiplus.com/general/privacy-policy?platform=android&header=0\""
    const val WEBVIEW_FAQ_HOT =
        "\"https://dev-webm.rctiplus.com/general/faq?platform=android&header=0\""
    const val WEBVIEW_UGC_BASE = "\"https://dev-hot.rctiplus.com\""
    const val WEBVIEW_TREBEL = "\"https://rctiplus.com/trebel/content_test\""
    const val TUS_UPLOAD_URL = "\"http://o-dev-api-tusd.rctiplus.com/files/\""
    const val CONVIVA_KEY_LICENSE = "\"ffc2bacab709e3c5eedc49af6520b33d3c204182\""
    const val CONVIVA_URL_GATEWAY = "\"https://rcti-test.testonly.conviva.com\""
    const val DEV_KEY_APPS_FLYER = "\"LPJWtQbzG94JJpnePh8z6A\""
    const val WP_BANNER_ADS = "\"/21865661642/RC_MIDDLE_APP_ANDROID\""
    const val LIVE_TV_BANNER_ADS = "\"/21865661642/RC_ANDROID-APP_LIVE_OVERLAY\""
    const val HOT_BANNER_ADS = "\"/21865661642/RC_HOT_ANDROID-APP_DISPLAY\""
    const val HOT_VIDEO_ADS =
        "\"https://pubads.g.doubleclick.net/gampad/ads?iu=/21865661642/RC_HOT_ANDROID-APP_VOD_PRE-ROLL&description_url=http%3A%2F%2Fhot.rctiplus.com%2F&tfcd=0&npa=0&sz=640x480&gdfp_req=1&output=vast&unviewed_position_start=1&env=vp&impl=s&correlator=\""
    const val MNC_ANALYTIC_KEY = "\"OGJkYzNjMWMtODNjOS00MDZmLWEwMDQtMzk5MzU5ZTIxNmZm\""
    const val MNC_ANALYTIC_URL = "\"rctiplus.mncanalytics.id\""
    const val GRAPHQL_KONG_API_KEY = "\"Tpa0pF9gLU989TKBslyWvhS6ghWXVm0V\""
    const val GA_property_id = "UA-158530597-2"
    const val firebase_sender_id = "464531657599"
//    const val qg_aiqua_appier_app_id = "c63c2960bf562e9ec2de"
    const val app_name = "RCTI+DEV"
//    const val facebook_app_id = "788507108365094-dev"
    const val facebook_app_id = "719222406535273"
//    const val fb_login_protocol_scheme = "fb788507108365094-dev"
    const val fb_login_protocol_scheme = "719222406535273"
//    const val facebook_client_token = "14c18d00e22e26df1a01d77bc5450aed-dev"
    const val facebook_client_token = "f471bddc9e14b21002de16c3c57b7d5b"
//    const val facebook_content_provider = "com.facebook.app.FacebookContentProvider788507108365094-dev"
    const val facebook_content_provider = "com.facebook.app.FacebookContentProvider719222406535273"
    const val HOST = "\"dev.rctiplus.com\""
    const val WWW_HOST = "\"www.dev.rctiplus.com\""
    const val NEWS_HOST = "\"dev-news.rctiplus.id\""
    const val M_HOST = "\"m-dev.rctiplus.com\""
    const val DEEPLINK_URL = "\"rctiplus://dev.rctiplus.com/radioplus\""
    const val CAPTCHA_SITE_KEY = "\"6LeJtx4hAAAAADfFSH5sUVzy-rHXLOvqovSfzGu9\""
    const val WS_API_KEY = "\"dXNlcm5hbWU6cGFzc3dvcmQ=\""
    const val TREBEL_API_BASE_URL = "\"https://mix.projectcarmen.com/mix/\""
    const val clevertap_account_id = "TEST-8WW-KRK-K66Z"
    const val clevertap_token = "TEST-323-00b"
}

object RcConfigField {
    const val applicationId = "com.fta.rc.rctitv"
    const val SERVICES_URL = "\"rc-api.rctiplus.com\""
    const val SERVICES_NEWS = "\"https://rc-api.rctiplus.com\""
    const val SERVICES_COUNTER = "\"https://hermes.mncplus.id\""
    const val SERVICES_UGC = "\"https://rc-api.rctiplus.com\""
    const val SERVICES_UGC_MONETIZATION = "\"https://rc-api.rctiplus.com\""
    const val SERVICES_PAYMENT = "\"https://rc-api-payment.rctiplus.com\""
    const val SERVICES_REWARDS = "\"https://rc-api-rewards.rctiplus.id\""
    const val SERVICES_TUS = "\"http://o-rc-api-tusd.rctiplus.com\""
    const val SERVICES_GRAPHQL = "\"https://hermes.mncplus.id/graphql\""
    const val SERVICES_KONG = "\"https://hermes.mncplus.id\""
    const val WEBVIEW_NEWS = "\"https://rc-webm.rctiplus.com\""
    const val WEBVIEW_ROOV = "\"https://dev-radioplus.mncplus.com/\""
    const val WEBVIEW_GAMES = "\"https://games-dev.rctiplus.com\""
    const val WEBVIEW_REWARDS = "\"https://rc-rewards.rctiplus.id\""
    const val WEBVIEW_TNC =
        "\"https://microsite.rctiplus.com/rctiplus-terms-and-conditions\""
    const val WEBVIEW_PRIVACY_POLICY =
        "\"https://microsite.rctiplus.com/rctiplus-privacy-policy\""
    const val WEBVIEW_FAQ = "\"https://microsite.rctiplus.com/rctiplus-faq\""
    const val WEBVIEW_TNC_HOT = "\"https://rc-hot.rctiplus.com/general/tnc?platform=android&header=0\""
    const val WEBVIEW_PRIVACY_POLICY_HOT =
        "\"https://rc-hot.rctiplus.com/general/privacy-policy?platform=android&header=0\""
    const val WEBVIEW_FAQ_HOT = "\"https://rc-hot.rctiplus.com/general/faq?platform=android&header=0\""
    const val WEBVIEW_UGC_BASE = "\"https://rc-hot.rctiplus.com\""
    const val WEBVIEW_TREBEL = "\"https://rctiplus.com/trebel/content_test\""
    const val TUS_UPLOAD_URL = "\"http://o-rc-api-tusd.rctiplus.com/files/\""
    const val CONVIVA_KEY_LICENSE = "\"ffc2bacab709e3c5eedc49af6520b33d3c204182\""
    const val CONVIVA_URL_GATEWAY = "\"https://rcti-test.testonly.conviva.com\""
    const val DEV_KEY_APPS_FLYER = "\"LPJWtQbzG94JJpnePh8z6A\""
    const val WP_BANNER_ADS = "\"/21865661642/RC_MIDDLE_APP_ANDROID\""
    const val LIVE_TV_BANNER_ADS = "\"/21865661642/RC_ANDROID-APP_OVERLAY_LIVE-TV\""
    const val HOT_BANNER_ADS = "\"/21865661642/RC_HOT_ANDROID-APP_DISPLAY\""
    const val HOT_VIDEO_ADS =
        "\"https://pubads.g.doubleclick.net/gampad/ads?iu=/21865661642/RC_HOT_ANDROID-APP_VOD_PRE-ROLL&description_url=http%3A%2F%2Fhot.rctiplus.com%2F&tfcd=0&npa=0&sz=640x480&gdfp_req=1&output=vast&unviewed_position_start=1&env=vp&impl=s&correlator=\""
    const val MNC_ANALYTIC_KEY = "\"OGJkYzNjMWMtODNjOS00MDZmLWEwMDQtMzk5MzU5ZTIxNmZm\""
    const val MNC_ANALYTIC_URL = "\"rctiplus.mncanalytics.id\""
    const val GRAPHQL_KONG_API_KEY = "\"hVi1p48IkWoe8Bb8ofp48BA2zOWltJuU\""
    const val GA_property_id = "UA-158530597-2"
    const val firebase_sender_id = "808988495158"
//    const val qg_aiqua_appier_app_id = "c63c2960bf562e9ec2de"
    const val app_name = "RCTI+RC"
//    const val facebook_app_id = "788507108365094"
    const val facebook_app_id = "1393751634730879"
//    const val fb_login_protocol_scheme = "fb788507108365094"
    const val fb_login_protocol_scheme = "1393751634730879"
//    const val facebook_client_token = "14c18d00e22e26df1a01d77bc5450aed"
    const val facebook_client_token = "4c9b0e90c8a764cc98991f4cbc34ce28"
//    const val facebook_content_provider = "com.facebook.app.FacebookContentProvider788507108365094"
    const val facebook_content_provider = "com.facebook.app.FacebookContentProvider1393751634730879"
    const val HOST = "\"rc.rctiplus.com\""
    const val WWW_HOST = "\"www.rc.rctiplus.com\""
    const val NEWS_HOST = "\"rc-news.rctiplus.id\""
    const val M_HOST = "\"m-rc.rctiplus.com\""
    const val DEEPLINK_URL = "\"rctiplus://rc.rctiplus.com/radioplus\""
    const val CAPTCHA_SITE_KEY = "\"6LeJtx4hAAAAADfFSH5sUVzy-rHXLOvqovSfzGu9\""
    const val WS_API_KEY = "\"UWRFekZlNGo6JUopdTtxOVF1XFtyQDUlag==\""
    const val TREBEL_API_BASE_URL = "\"https://mix.projectcarmen.com/mix/\""
    const val clevertap_account_id = "TEST-8WW-KRK-K66Z"
    const val clevertap_token = "TEST-323-00b"
}

object ProdConfigField {
    const val applicationId = "com.fta.rctitv"
    const val SERVICES_URL = "\"api.rctiplus.com\""
    const val SERVICES_NEWS = "\"https://api-v2.rctiplus.com\""
    const val SERVICES_COUNTER = "\"https://api-hot.rctiplus.com\""
    const val SERVICES_UGC = "\"https://api-hot.rctiplus.com\""
    const val SERVICES_UGC_MONETIZATION = "\"https://api-hot.rctiplus.com\""
    const val SERVICES_PAYMENT = "\"https://api-payment.rctiplus.com\""
    const val SERVICES_REWARDS = "\"https://api-rewards.rctiplus.com\""
    const val SERVICES_TUS = "\"http://api-tus.rctiplus.com\""
    const val SERVICES_GRAPHQL = "\"https://zeus.rcti.plus/graphql\""
    const val SERVICES_KONG = "\"https://zeus.rcti.plus\""
    const val WEBVIEW_NEWS = "\"https://m.rctiplus.com\""
    const val WEBVIEW_ROOV = "\"https://radio.rctiplus.com\""
    const val WEBVIEW_GAMES = "\"https://games.rctiplus.com\""
    const val WEBVIEW_REWARDS = "\"https://rewards.rctiplus.id\""
    const val WEBVIEW_TNC = "\"https://microsite.rctiplus.com/rctiplus-terms-and-conditions\""
    const val WEBVIEW_PRIVACY_POLICY =
        "\"https://microsite.rctiplus.com/rctiplus-privacy-policy\""
    const val WEBVIEW_FAQ = "\"https://microsite.rctiplus.com/rctiplus-faq\""
    const val WEBVIEW_TNC_HOT = "\"https://hot.rctiplus.com/general/tnc?platform=android&header=0\""
    const val WEBVIEW_PRIVACY_POLICY_HOT =
        "\"https://hot.rctiplus.com/general/privacy-policy?platform=android&header=0\""
    const val WEBVIEW_FAQ_HOT = "\"https://hot.rctiplus.com/general/faq?platform=android&header=0\""
    const val WEBVIEW_UGC_BASE = "\"https://hot.rctiplus.com\""
    const val WEBVIEW_TREBEL = "\"https://www.rctiplus.com/trebel/content\""
    const val TUS_UPLOAD_URL = "\"http://api-tus.rctiplus.com/files/\""
    const val CONVIVA_KEY_LICENSE = "\"ff84ae928c3b33064b76dec08f12500465e59a6f\""
    const val CONVIVA_URL_GATEWAY = "\"\""
    const val DEV_KEY_APPS_FLYER = "\"LPJWtQbzG94JJpnePh8z6A\""
    const val WP_BANNER_ADS = "\"/21865661642/PRO_MIDDLE_APP_ANDROID\""
    const val LIVE_TV_BANNER_ADS = "\"/21865661642/PRO_ANDROID-APP_OVERLAY_LIVE-TV\""
    const val HOT_BANNER_ADS = "\"/21865661642/PRO_HOT_ANDROID-APP_DISPLAY\""
    const val HOT_VIDEO_ADS =
        "\"https://pubads.g.doubleclick.net/gampad/ads?iu=/21865661642/PRO_HOT_ANDROID-APP_VOD_PRE-ROLL&description_url=https%3A%2F%2Fhot.rctiplus.com%2F&tfcd=0&npa=0&sz=640x480&gdfp_req=1&output=vast&unviewed_position_start=1&env=vp&impl=s&correlator=\""
    const val MNC_ANALYTIC_KEY = "\"OGJkYzNjMWMtODNjOS00MDZmLWEwMDQtMzk5MzU5ZTIxNmZm\""
    const val MNC_ANALYTIC_URL = "\"rctiplus.mncanalytics.id\""
    const val GRAPHQL_KONG_API_KEY = "\"R4xWKbkpq46o51NBqPSyVdsYGysi0yNr\""
    const val GA_property_id ="UA-158530597-2"
    const val firebase_sender_id ="102225357690"
//    const val qg_aiqua_appier_app_id ="3be8515a1c2359442dfd"
    const val app_name ="RCTI+"
    const val facebook_app_id ="233089465736145"
    const val fb_login_protocol_scheme ="fb233089465736145"
    const val facebook_client_token ="b993220d954f51d2de66423f4d79c89d"
    const val facebook_content_provider ="com.facebook.app.FacebookContentProvider233089465736145"
    const val HOST ="\"rctiplus.com\""
    const val WWW_HOST ="\"www.rctiplus.com\""
    const val NEWS_HOST ="\"news.rctiplus.id\""
    const val M_HOST ="\"m.rctiplus.com\""
    const val DEEPLINK_URL ="\"rctiplus://rctiplus.com/radioplus\""
    const val CAPTCHA_SITE_KEY = "\"6LeJvR4hAAAAAH1CXc1q0yPPG0b4mTspivDEiK0j\""
    const val WS_API_KEY = "\"Ujdza1NueE46LHB9OTY1QGpCd0UlOCZaOw==\""
    const val TREBEL_API_BASE_URL = "\"https://mix.projectcarmen.com/mix/\""
    const val clevertap_account_id = "8RZ-886-W46Z"
    const val clevertap_token = "6bb-12b"
}