package com.raydev.shared.util

object KeyShared {
    val PREF_KEYS = "muslim_key"
    val IMSAK_TIME = "imsak_time"
    val IMSAK_STATUS = "imsak_status"
    val SUBUH_TIME = "subuh_time"
    val SUBUH_STATUS = "subuh_status"
    val DHUHUR_TIME = "dhuhur_time"
    val DHUHUR_STATUS = "dhuhur_status"
    val ASHAR_TIME = "ashar_time"
    val ASHAR_STATUS = "ashar_status"
    val MAGHRIB_TIME = "maghrib_time"
    val MAGHRIB_STATUS = "maghrib_status"
    val ISYA_TIME = "isya_time"
    val ISYA_STATUS = "isya_status"
    val PREF_KEY_CALCULATION_METHOD = "PREF_KEY_CALCULATION_METHOD"
    val PREF_KEY_ASR_JURISTIC = "PREF_KEY_ASR_JURISTIC"
    val PREF_KEY_HIGHER_LATITUDES = "PREF_KEY_HIGHER_LATITUDES"
    val PREF_KEY_FAJR_OFFSET = "PREF_KEY_FAJR_OFFSET"
    val PREF_KEY_DHUHR_OFFSET = "PREF_KEY_DHUHR_OFFSET"
    val PREF_KEY_ASR_OFFSET = "PREF_KEY_ASR_OFFSET"
    val PREF_KEY_MAGHRIB_OFFSET = "PREF_KEY_MAGHRIB_OFFSET"
    val PREF_KEY_ISYA_OFFSET = "PREF_KEY_ISYA_OFFSET"
    val PREF_KEY_PRAYERTIME = "PREF_KEY_PRAYERTIME"
    val PREF_KEY_USER_COORDINATES = "PREF_KEY_USER_COORDINATES"
    val PREF_KEY_USER_CITY = "PREF_KEY_USER_CITY"
    val PREF_KEY_QURAN_LAST_READ = "PREF_KEY_QURAN_LAST_READ"
}